// IELTS-style question sets for each reading passage (same order as readings.js).
// h:     matching headings — [paragraph letter, correct heading]; extra: distractor headings
// tfng:  [statement, "TRUE" | "FALSE" | "NOT GIVEN"]
// gap:   [sentence with ___, [accepted answers]] — NO MORE THAN TWO WORDS AND/OR A NUMBER from the passage
// Multiple-choice questions come from the `questions` in readings.js.
window.IELTS = [
{h:[["A","The human cost of a pig disease"],["B","Emergency measures and what the data revealed"],["C","Many groups working together"]],
 extra:["A new vaccine for African swine fever","Why trucks should be banned"],
 tfng:[["The outbreak affected villages in the north of Laos.","FALSE"],["Reporting sick pigs became compulsory.","TRUE"],["The district team received funding from an international organisation.","NOT GIVEN"]],
 gap:[["During surveillance, the team visited farms every week and collected ___.",["blood samples"]],["The highest prevalence was found in villages near the ___.",["main road"]]]},
{h:[["A","Signs of a sick animal"],["B","A step-by-step examination"],["C","A long-standing problem"],["D","Treatment and outlook"]],
 extra:["Choosing the right antibiotic","Why goats are difficult patients"],
 tfng:[["The goat had not eaten for two days.","TRUE"],["The heart and lungs sounded abnormal.","FALSE"],["The farmer had taken the goat to another vet before.","NOT GIVEN"]],
 gap:[["The swelling on the goat's neck was an ___.",["abscess"]],["The goat had been limping for ___.",["months"]]]},
{h:[["A","Getting the amount right"],["B","Checking safety and choosing a route"],["C","How farmers can create resistant bacteria"],["D","Protecting consumers"]],
 extra:["The history of antibiotics","Vaccines as an alternative to drugs"],
 tfng:[["Giving too much of a drug can damage the kidneys.","TRUE"],["Intravenous treatment works more slowly than an injection into the muscle.","FALSE"],["Most farmers in Laos stop treatment early.","NOT GIVEN"]],
 gap:[["Some drugs should not be given to ___ animals.",["pregnant"]],["Stopping treatment early is an example of poor ___.",["compliance"]]]},
{h:[["A","The research question"],["B","Designing the study"],["C","Avoiding unfair results"],["D","What happens after data collection"]],
 extra:["Results of a national survey","The cost of rabies vaccines"],
 tfng:[["The study will take place in three districts.","TRUE"],["The student will visit only houses near the main road.","FALSE"],["The student has already received funding for the project.","NOT GIVEN"]],
 gap:[["Each respondent will answer a short ___.",["questionnaire"]],["To reduce bias, villages will be chosen ___.",["at random"]]]},
{h:[["A","The main conclusion of a new study"],["B","Evidence of faster reporting"],["C","Obstacles facing local workers"],["D","Ways to strengthen the system"]],
 extra:["Why farmers distrust officials","Training doctors in rural hospitals"],
 tfng:[["The report was published last month.","TRUE"],["Villages without trained workers reported outbreaks earlier.","FALSE"],["The report was written by government officials.","NOT GIVEN"]],
 gap:[["Some workers have not been ___ for months.",["paid"]],["Regular ___ courses can improve workers' skills.",["refresher"]]]},
{h:[["A","Introducing the farmer"],["B","Feeding cows through the year"],["C","A stressful stage for young animals"],["D","Improving the herd"]],
 extra:["Selling milk in the city","Keeping chickens healthy"],
 tfng:[["Mr Somchai keeps more chickens than cows.","TRUE"],["Calves are separated from their mothers at about six months.","FALSE"],["Mr Somchai sells his milk to a large company.","NOT GIVEN"]],
 gap:[["After calving, the main goal is to keep the milk ___ high.",["yield"]],["He improved his young stock by using a stronger ___.",["bull"]]]},
{h:[["A","The basic principle"],["B","Controlling who enters the farm"],["C","The risk of bringing in new stock"],["D","Other routes of infection"]],
 extra:["Treating sick pigs with antibiotics","The cost of building a farm"],
 tfng:[["Visitors should disinfect both their boots and their hands.","TRUE"],["New animals that look healthy do not need quarantine.","FALSE"],["Most pig farms in Laos have a footbath.","NOT GIVEN"]],
 gap:[["Feed and water should be stored in clean, closed ___.",["containers"]],["Farms need good drainage and ___ control.",["insect"]]]},
{h:[["A","A sudden increase in deaths"],["B","Too many fish, too little oxygen"],["C","Clues from the gills and skin"],["D","Practical solutions"]],
 extra:["Selling fish at the market","The history of tilapia farming"],
 tfng:[["The team arrived at the pond early in the morning.","TRUE"],["The farmer had bought 800 fingerlings.","FALSE"],["The hatchery was located in Thailand.","NOT GIVEN"]],
 gap:[["The fish used up oxygen quickly, especially at ___.",["night"]],["The team advised the farmer to add an ___.",["aerator"]]]},
{h:[["A","A species under threat"],["B","An arrest at the border"],["C","Weeks of care"],["D","Return to the wild"]],
 extra:["Pangolins as pets","Traditional medicine markets"],
 tfng:[["Police found three pangolins in a bag.","TRUE"],["The pangolins stayed at the centre for six months.","FALSE"],["The pangolins were fitted with tracking devices before release.","NOT GIVEN"]],
 gap:[["During recovery, the pangolins lived in a quiet ___ enclosure.",["captive"]],["The team carried out the release at ___.",["night"]]]},
{h:[["A","The main argument"],["B","Why vaccinated birds do better"],["C","A costly decision"],["D","Help with the cost"]],
 extra:["How Newcastle disease spreads","Choosing the best breed of chicken"],
 tfng:[["Newcastle disease can kill almost a whole flock in a few days.","TRUE"],["The neighbour's brother lost half of his chickens.","FALSE"],["The vaccine must be given every month.","NOT GIVEN"]],
 gap:[["Healthy birds can be sold at a higher ___.",["price"]],["The district now offers a small ___ for the vaccine.",["subsidy"]]]},
{h:[["A","What the graph shows"],["B","A period of growth"],["C","A sudden collapse"],["D","Slow recovery and future demand"]],
 extra:["Prices of pork in the capital","The spread of the disease in Europe"],
 tfng:[["Pig numbers were highest in 2019.","TRUE"],["Large commercial farms suffered most of the losses in 2020.","FALSE"],["The province introduced a vaccine in 2021.","NOT GIVEN"]],
 gap:[["In 2020, pig numbers fell to just ___.",["40,000","40000"]],["From 2023 to 2025, the total stayed at around ___.",["90,000","90000"]]]},
{h:[["A","A difficult policy"],["B","The case in favour"],["C","The impact on families"],["D","A possible compromise"]],
 extra:["The history of animal vaccines","How to identify sick animals"],
 tfng:[["Healthy animals may be killed during an outbreak.","TRUE"],["The writer believes culling should never be used.","FALSE"],["Most countries in Asia pay full compensation.","NOT GIVEN"]],
 gap:[["Low or late compensation may lead farmers to ___ sick animals.",["hide"]],["According to the writer, the main benefit of fair compensation is ___.",["trust"]]]},
{h:[["A","Diseases that jump species"],["B","Hidden carriers and new victims"],["C","Different patterns of disease"],["D","Why reporting must be quick"]],
 extra:["How vaccines are made","The first human vaccine"],
 tfng:[["About three quarters of new infectious diseases in humans come from animals.","TRUE"],["Reservoir species usually become very sick.","FALSE"],["Bats carry more viruses than any other animal.","NOT GIVEN"]],
 gap:[["Rabies is described as ___ in parts of Asia.",["endemic"]],["The time between infection and the first signs of illness is the ___.",["incubation period"]]]},
{h:[["A","Why coverage matters"],["B","Keeping vaccines cold"],["C","Different kinds of vaccine"],["D","Follow-up doses and results"]],
 extra:["The cost of a rabies campaign","Treating people after dog bites"],
 tfng:[["The district aims to vaccinate at least 70 percent of dogs.","TRUE"],["The rabies vaccine used by the district is a live vaccine.","FALSE"],["The campaign is funded by an international organisation.","NOT GIVEN"]],
 gap:[["Vaccines must be kept between 2 and 8 degrees ___.",["Celsius"]],["All dogs need a new dose every ___.",["year"]]]},
{h:[["A","Good results begin outside the laboratory"],["B","Collecting and preparing samples"],["C","Methods used by technicians"],["D","The limits of testing"]],
 extra:["Training laboratory staff","Sending samples abroad"],
 tfng:[["Blood is spun in a centrifuge to separate the serum.","TRUE"],["Bacteria usually grow in culture within one hour.","FALSE"],["PCR is more expensive than ELISA.","NOT GIVEN"]],
 gap:[["Each specimen must be collected in a ___ tube.",["sterile"]],["Each reagent must be stored at the right ___.",["temperature"]]]},
{h:[["A","A nervous first experience"],["B","Preparing the patient"],["C","The operation itself"],["D","Care after surgery"]],
 extra:["Choosing a career in surgery","Risks of anaesthesia in old dogs"],
 tfng:[["The operation was a castration.","TRUE"],["The wound was closed in one layer.","FALSE"],["The surgery took two hours.","NOT GIVEN"]],
 gap:[["The team wore sterile gloves and ___.",["gowns"]],["After ten days, the dog was running and ___ as normal.",["playing"]]]},
{h:[["A","Targets for a dairy herd"],["B","Detecting heat and improving calves"],["C","Nine months of pregnancy"],["D","Problems around birth"]],
 extra:["Selling calves at market","Housing cows in the rainy season"],
 tfng:[["A heifer should have her first calf at about two years old.","TRUE"],["Gestation in cattle lasts about six months.","FALSE"],["Artificial insemination is cheaper than keeping a bull.","NOT GIVEN"]],
 gap:[["Dystocia is common in ___ cows.",["young"]],["Brucellosis is a disease that can cause ___.",["abortion"]]]},
{h:[["A","Why cattle lose weight"],["B","The effects of poor feeding"],["C","Three practical steps"],["D","Planning and observation"]],
 extra:["Growing rice for animal feed","The price of concentrate"],
 tfng:[["In the dry season, grass contains fewer nutrients.","TRUE"],["A balanced ration must be expensive.","FALSE"],["Treated rice straw is the most popular feed in Laos.","NOT GIVEN"]],
 gap:[["A mineral supplement is often given as a salt ___.",["block"]],["Animals producing milk may need rice bran or ___.",["maize"]]]},
{h:[["A","Pigs and poor families"],["B","Who earns the money"],["C","Barriers to fair prices"],["D","Recommendations for change"]],
 extra:["Pork in Lao cooking","Exporting pork to China"],
 tfng:[["Most pigs in Laos are raised by smallholder families.","TRUE"],["Farmers received most of the final revenue.","FALSE"],["The study was funded by the World Bank.","NOT GIVEN"]],
 gap:[["Many villages are far from good ___.",["roads"]],["Farmer ___ can sell together to get better prices.",["groups"]]]},
{h:[["A","An organisation's responsibility"],["B","Starting a project"],["C","Money and training"],["D","Working across ministries"],["E","Measuring success"]],
 extra:["Problems with corruption","Recruiting international staff"],
 tfng:[["Projects usually begin when a government asks for help.","TRUE"],["Project funding usually comes from local farmers.","FALSE"],["Most projects last five years.","NOT GIVEN"]],
 gap:[["The organisation works in ___ with the ministry.",["partnership"]],["New regulation may be needed to control the sale of ___.",["antibiotics"]]]},
{h:[["A","The other half of the job"],["B","A dangerous false belief"],["C","Simple messages work best"],["D","Worries about money"],["E","Building a lasting relationship"]],
 extra:["Training village health workers","The science of rabies vaccines"],
 tfng:[["At first, many villagers did not want to listen.","TRUE"],["The vaccine for people was expensive at the district hospital.","FALSE"],["The team visited five villages.","NOT GIVEN"]],
 gap:[["The team used pictures and short ___ to explain key messages.",["stories"]],["Families were advised to wash a bite wound for ___ minutes.",["fifteen","15"]]]},
{h:[["A","An unpredictable climate"],["B","New threats to animal health"],["C","Diseases moving to new places"],["D","Part of the problem"],["E","Ways to cope"]],
 extra:["Government policy on emissions","Rising prices of rice"],
 tfng:[["Heat stress can kill pigs kept in hot, crowded houses.","TRUE"],["Local breeds tolerate heat less well than other breeds.","FALSE"],["Laos has banned the burning of manure.","NOT GIVEN"]],
 gap:[["Flooding spreads diseases such as ___.",["leptospirosis"]],["Overgrazing causes land ___.",["degradation"]]]},
{h:[["A","Purpose of the survey"],["B","Describing the households"],["C","The main result"],["D","Comparing with the past"]],
 extra:["Why owners refuse vaccination","The cost of the survey"],
 tfng:[["The survey included 300 households.","TRUE"],["The average number of dogs per household was 2.","FALSE"],["Most owners said vaccines were too expensive.","NOT GIVEN"]],
 gap:[["The true percentage is probably between 40 and ___ percent.",["52"]],["The survey will be repeated every ___.",["two years","2 years"]]]},
{h:[],extra:[],
 tfng:[["The workshop was originally planned for 10 November.","TRUE"],["The writer suggests moving the workshop to 14 November.","FALSE"],["Ms Chanthavong works for the Ministry of Health.","NOT GIVEN"],["The venue must be booked before Friday.","TRUE"]],
 gap:[["The writer attached a draft ___ for the workshop.",["agenda"]],["The writer will send an updated list of ___.",["participants"]],["District vets will be busy with the vaccination ___.",["campaign"]]]},
{h:[["A","An unrecognised role"],["B","Checking animals and meat"],["C","Keeping things clean"],["D","The importance of cold"],["E","Drugs and tracing"]],
 extra:["Cooking meat safely at home","Export rules for pork"],
 tfng:[["Animals should be checked before and after slaughter.","TRUE"],["Foodborne infections are most serious in young adults.","FALSE"],["Most slaughterhouses in Laos have refrigerators.","NOT GIVEN"]],
 gap:[["Bacteria such as ___ can spread from raw meat to cooked food.",["Salmonella"]],["Many countries give animals ___ to improve traceability.",["ear tags"]]]},
{h:[["A","An unexplained death"],["B","Findings in the chest"],["C","Findings in the abdomen"],["D","A likely diagnosis"],["E","Differences in other species"]],
 extra:["Treating pigs with fever","Vaccinating pigs against African swine fever"],
 tfng:[["The examination was carried out the same afternoon.","TRUE"],["The liver was severely damaged.","FALSE"],["The farm had lost other pigs the week before.","NOT GIVEN"]],
 gap:[["The skin on the ears and belly was dark ___.",["red"]],["In a dairy cow, the udder is examined for signs of ___.",["mastitis"]]]},
{h:[["A","A deadly cattle disease"],["B","Effects on people"],["C","Vaccines and surveillance"],["D","A historic achievement"],["E","Lessons for today"]],
 extra:["How rinderpest was first discovered","The cost of the global campaign"],
 tfng:[["In some outbreaks, more than 90 percent of infected animals died.","TRUE"],["Rinderpest was the first disease that humans eradicated.","FALSE"],["The global campaign was led by one country.","NOT GIVEN"]],
 gap:[["Farmers needed cattle for ___ and food.",["ploughing"]],["Where the virus remained in wild animals, ___ became even more important.",["surveillance"]]]},
{h:[["A","The writer's goal"],["B","Understanding farmers' feelings"],["C","Careful record keeping"],["D","Teamwork and flexibility"],["E","A preventive attitude"]],
 extra:["Plans for further study abroad","Experience in small-animal surgery"],
 tfng:[["The writer is in the final year of veterinary study.","TRUE"],["The writer's supervisor describes the writer as disorganised.","FALSE"],["The writer has worked in China.","NOT GIVEN"]],
 gap:[["In the laboratory, the writer keeps detailed records of every ___.",["sample"]],["Plans often changed when roads were ___.",["flooded"]]]},
{h:[["A","A dramatic change in diets"],["B","More people, more money, more cities"],["C","From villages to large farms"],["D","Trade across borders"],["E","Challenges for rural areas"]],
 extra:["The rise of vegetarian diets","Fish farming in the Mekong"],
 tfng:[["Rising incomes allow families to buy more meat, eggs and milk.","TRUE"],["Globalisation makes food more expensive.","FALSE"],["Most young people prefer to work in factories.","NOT GIVEN"]],
 gap:[["Large commercial farms are found especially near big ___.",["cities"]],["Many remote villages have limited access to veterinary ___.",["services"]]]},
{h:[["A","Defining One Health"],["B","The evidence behind the idea"],["C","Planning together"],["D","The contribution of veterinarians"]],
 extra:["The history of the WHO","Funding problems in rural clinics"],
 tfng:[["Antimicrobial resistance affects both hospitals and farms.","TRUE"],["Under One Health, each ministry works alone.","FALSE"],["Laos was the first country to adopt One Health.","NOT GIVEN"]],
 gap:[["Deforestation and flooding are examples of environmental ___.",["factors"]],["The goal is to end human deaths from rabies by ___.",["2030"]]]}
];
