// Daily vocabulary bank. Day 1 is 2026-09-26; one set of 10 words per day.
// Each word: [word, part of speech, Thai meaning, example sentence]
window.WORD_START = "2026-09-26";
window.WORD_DAYS = [
{theme:"One Health และโรคระบาด", words:[
["outbreak","n.","การระบาด (ของโรค)","An outbreak of African swine fever was reported in three provinces."],
["surveillance","n.","การเฝ้าระวัง (โรค)","Active surveillance helps detect diseases before they spread."],
["zoonotic","adj.","ติดต่อจากสัตว์สู่คนได้","Rabies is a zoonotic disease that kills thousands of people every year."],
["transmission","n.","การแพร่เชื้อ","The virus has a high rate of transmission between pigs."],
["mitigate","v.","บรรเทา, ลดความรุนแรง","Vaccination can mitigate the economic impact of the disease."],
["prevalence","n.","ความชุก (สัดส่วนที่ป่วยอยู่ ณ เวลาหนึ่ง)","The prevalence of parasites was higher in the rainy season."],
["stakeholder","n.","ผู้มีส่วนได้ส่วนเสีย","Farmers are key stakeholders in disease control programmes."],
["contain","v.","ควบคุมไม่ให้แพร่กระจาย","Authorities moved quickly to contain the outbreak."],
["livelihood","n.","อาชีพ, แหล่งรายได้ในการดำรงชีวิต","Livestock diseases threaten the livelihoods of rural families."],
["mandatory","adj.","ที่บังคับ, ต้องทำตามกฎ","Reporting of foot-and-mouth disease is mandatory."]]},
{theme:"การตรวจร่างกายสัตว์", words:[
["lethargic","adj.","ซึม, ไม่มีแรง","The calf was lethargic and refused to drink milk."],
["dehydrated","adj.","ขาดน้ำ","Severely dehydrated piglets need fluids immediately."],
["lesion","n.","รอยโรค","Vesicular lesions were found on the tongue and feet."],
["lameness","n.","อาการขาเจ็บ, เดินกะเผลก","Lameness is a common welfare problem in dairy cattle."],
["inflammation","n.","การอักเสบ","Redness and swelling are signs of inflammation."],
["abscess","n.","ฝี","The vet drained the abscess on the goat's neck."],
["prognosis","n.","การพยากรณ์โรค (แนวโน้มการหาย)","The prognosis is good if treatment starts early."],
["palpate","v.","คลำตรวจ","She palpated the abdomen to check for pain."],
["auscultation","n.","การฟังเสียงด้วยหูฟัง","Auscultation revealed abnormal lung sounds."],
["chronic","adj.","เรื้อรัง","Chronic diarrhoea caused the dog to lose weight."]]},
{theme:"การรักษาและยา", words:[
["dosage","n.","ขนาดยา","Always calculate the dosage according to body weight."],
["administer","v.","ให้ยา","The drug should be administered by intramuscular injection."],
["adverse","adj.","ไม่พึงประสงค์, เป็นผลเสีย","Report any adverse reactions after vaccination."],
["contraindication","n.","ข้อห้ามใช้","Pregnancy is a contraindication for this drug."],
["efficacy","n.","ประสิทธิผล (ของยาหรือวัคซีน)","The trial tested the efficacy of the new dewormer."],
["prescribe","v.","สั่งจ่ายยา","Only a veterinarian can prescribe antibiotics."],
["resistance","n.","การดื้อ (ยา)","Overuse of antibiotics leads to antimicrobial resistance."],
["intravenous","adj.","ทางหลอดเลือดดำ","Intravenous fluids were given to the collapsed cow."],
["withdrawal period","n.","ระยะหยุดยา (ก่อนส่งเนื้อหรือนม)","Milk cannot be sold during the withdrawal period."],
["compliance","n.","การปฏิบัติตาม (คำแนะนำ)","Owner compliance with the treatment plan was poor."]]},
{theme:"วิธีวิจัย", words:[
["hypothesis","n.","สมมติฐาน","Our hypothesis is that vaccinated herds have fewer outbreaks."],
["sample size","n.","ขนาดตัวอย่าง","A larger sample size would give more reliable results."],
["variable","n.","ตัวแปร","Age and breed were included as variables in the model."],
["methodology","n.","ระเบียบวิธีวิจัย","The methodology section describes how data were collected."],
["bias","n.","อคติ, ความลำเอียง (ในข้อมูล)","Selecting only sick animals may introduce bias."],
["significant","adj.","มีนัยสำคัญ","There was a significant difference between the two groups."],
["correlation","n.","ความสัมพันธ์ (ทางสถิติ)","We found a correlation between rainfall and tick numbers."],
["respondent","n.","ผู้ตอบแบบสอบถาม","Most respondents kept fewer than ten pigs."],
["questionnaire","n.","แบบสอบถาม","A questionnaire was used to interview 120 farmers."],
["cross-sectional","adj.","แบบภาคตัดขวาง (เก็บข้อมูล ณ จุดเวลาเดียว)","We conducted a cross-sectional study in five districts."]]},
{theme:"กริยาสำหรับงานเขียนวิชาการ", words:[
["demonstrate","v.","แสดงให้เห็น, พิสูจน์","The results demonstrate the value of early vaccination."],
["indicate","v.","บ่งชี้","These findings indicate a need for better biosecurity."],
["highlight","v.","เน้นให้เห็นความสำคัญ","The report highlights gaps in disease reporting."],
["suggest","v.","ชี้ให้เห็นว่า (อาจจะ)","The data suggest that the virus entered through trade."],
["emphasise","v.","ย้ำ, เน้น","The authors emphasise the role of farmer education."],
["illustrate","v.","อธิบายให้เห็นภาพ, ยกตัวอย่าง","Figure 2 illustrates the spread of cases over time."],
["contribute","v.","มีส่วนทำให้เกิด","Poor hygiene contributed to the outbreak."],
["undermine","v.","บ่อนทำลาย, ทำให้อ่อนลง","Fake medicines undermine trust in veterinary services."],
["facilitate","v.","อำนวยความสะดวก, ทำให้ง่ายขึ้น","Mobile phones facilitate faster disease reporting."],
["enhance","v.","เพิ่ม, ยกระดับ","Training can enhance the skills of village vets."]]},
{theme:"การผลิตปศุสัตว์", words:[
["livestock","n.","ปศุสัตว์","Livestock provide food and income for many households."],
["herd","n.","ฝูง (โค กระบือ สุกร)","The whole herd was tested for tuberculosis."],
["flock","n.","ฝูง (สัตว์ปีก แพะ แกะ)","A flock of 500 chickens died within two days."],
["yield","n.","ผลผลิต","Good nutrition increases milk yield."],
["fodder","n.","อาหารหยาบสำหรับสัตว์","Farmers store fodder for the dry season."],
["breeding","n.","การผสมพันธุ์, การปรับปรุงพันธุ์","Careful breeding improved growth rates."],
["calving","n.","การคลอดลูกโค","Most calving takes place at the start of the rainy season."],
["weaning","n.","การหย่านม","Weaning stress can lower piglet immunity."],
["carcass","n.","ซากสัตว์","Carcasses must be buried or burned safely."],
["productivity","n.","ผลิตภาพ, ประสิทธิภาพการผลิต","Disease control improves farm productivity."]]},
{theme:"ความปลอดภัยทางชีวภาพ", words:[
["biosecurity","n.","ความปลอดภัยทางชีวภาพ","Strict biosecurity keeps diseases out of the farm."],
["disinfect","v.","ฆ่าเชื้อ","Disinfect boots before entering the pig house."],
["quarantine","n.","การกักโรค","New animals should stay in quarantine for 30 days."],
["contaminated","adj.","ปนเปื้อน","Contaminated feed can carry the virus."],
["pathogen","n.","เชื้อก่อโรค","Some pathogens survive for months in the soil."],
["vector","n.","พาหะนำโรค (เช่น แมลง)","Mosquitoes are vectors of Japanese encephalitis."],
["carrier","n.","ตัวอมโรค","Recovered animals may become carriers of the virus."],
["footbath","n.","อ่างจุ่มเท้าฆ่าเชื้อ","Change the footbath solution every day."],
["isolate","v.","แยก (สัตว์ป่วย)","Isolate sick animals from the rest of the herd."],
["restrict","v.","จำกัด","Movement of pigs was restricted during the outbreak."]]},
{theme:"สุขภาพสัตว์น้ำ", words:[
["aquaculture","n.","การเพาะเลี้ยงสัตว์น้ำ","Aquaculture is growing quickly in Laos."],
["gill","n.","เหงือก","Pale gills may indicate anaemia or parasites."],
["fingerling","n.","ลูกปลาขนาดนิ้ว","The farmer stocked 5,000 tilapia fingerlings."],
["stocking density","n.","ความหนาแน่นในการปล่อยเลี้ยง","High stocking density increases stress and disease."],
["dissolved oxygen","n.","ออกซิเจนละลายน้ำ","Fish gasp at the surface when dissolved oxygen is low."],
["water quality","n.","คุณภาพน้ำ","Most fish health problems start with poor water quality."],
["hatchery","n.","โรงเพาะฟัก","Healthy fry from a good hatchery reduce losses."],
["mortality","n.","อัตราการตาย","Mortality rose sharply after the heavy rain."],
["parasite","n.","ปรสิต","Parasites were seen on the skin under the microscope."],
["feed conversion ratio","n.","อัตราแลกเนื้อ","A lower feed conversion ratio means more efficient growth."]]},
{theme:"สัตว์ป่าและการอนุรักษ์", words:[
["endangered","adj.","ใกล้สูญพันธุ์","The Asian elephant is an endangered species."],
["habitat","n.","ถิ่นที่อยู่อาศัย","Forest loss destroys the habitat of many animals."],
["poaching","n.","การล่าสัตว์ผิดกฎหมาย","Poaching is a major threat to wildlife in the region."],
["conservation","n.","การอนุรักษ์","Vets play an important role in wildlife conservation."],
["captive","adj.","ที่ถูกเลี้ยงในกรง, ถูกกักขัง","Captive bears often have dental problems."],
["sedate","v.","ทำให้สงบ, วางยาซึม","The team sedated the tiger before the examination."],
["biodiversity","n.","ความหลากหลายทางชีวภาพ","Healthy ecosystems depend on biodiversity."],
["trafficking","n.","การลักลอบค้า","Wildlife trafficking can spread new diseases."],
["rehabilitation","n.","การฟื้นฟู","The pangolin was sent to a rehabilitation centre."],
["release","v.","ปล่อยคืน (สู่ธรรมชาติ)","The birds were released after they recovered."]]},
{theme:"คำเชื่อมสำหรับ IELTS", words:[
["however","adv.","อย่างไรก็ตาม","The drug is effective; however, it is expensive."],
["moreover","adv.","ยิ่งไปกว่านั้น","Vaccination is cheap. Moreover, it protects the whole herd."],
["consequently","adv.","ดังนั้น, ผลที่ตามมาคือ","Feed prices rose; consequently, many farmers sold their pigs."],
["nevertheless","adv.","ถึงกระนั้นก็ตาม","The weather was bad. Nevertheless, the survey was completed."],
["whereas","conj.","ในขณะที่ (เปรียบเทียบความต่าง)","Cattle are raised for meat, whereas buffalo are also used for work."],
["furthermore","adv.","นอกจากนี้","Furthermore, the study found higher rates in the north."],
["therefore","adv.","ดังนั้น","The virus survives in pork; therefore, swill feeding is dangerous."],
["despite","prep.","แม้ว่า","Despite the cost, farmers chose to vaccinate."],
["in contrast","phr.","ในทางตรงกันข้าม","In contrast, urban farms reported fewer cases."],
["as a result","phr.","ผลก็คือ","As a result, pork prices increased."]]},
{theme:"บรรยายกราฟ (Writing Task 1)", words:[
["fluctuate","v.","ขึ้นลง, ผันผวน","The number of cases fluctuated throughout the year."],
["peak","v.","ขึ้นถึงจุดสูงสุด","Cases peaked in July at 450."],
["plummet","v.","ลดลงอย่างรวดเร็วและมาก","Pig prices plummeted after the outbreak."],
["surge","n.","การเพิ่มขึ้นอย่างฉับพลัน","There was a surge in demand for vaccines."],
["steady","adj.","คงที่, สม่ำเสมอ","Milk production showed a steady increase."],
["decline","v.","ลดลง","The prevalence declined from 20% to 8%."],
["gradual","adj.","ค่อยเป็นค่อยไป","There was a gradual rise in fish exports."],
["remain stable","phr.","คงที่","Poultry numbers remained stable over the decade."],
["account for","phr.","คิดเป็น (สัดส่วน)","Pigs accounted for 40% of all livestock."],
["proportion","n.","สัดส่วน","A large proportion of farmers had never vaccinated."]]},
{theme:"แสดงความคิดเห็น (Writing Task 2)", words:[
["advocate","v.","สนับสนุน, เรียกร้อง","Many experts advocate a One Health approach."],
["controversial","adj.","เป็นที่ถกเถียง","Culling healthy animals is a controversial policy."],
["drawback","n.","ข้อเสีย","The main drawback of this method is its cost."],
["benefit","n.","ประโยชน์","Vaccination brings clear economic benefits."],
["perspective","n.","มุมมอง","From a farmer's perspective, time is money."],
["justify","v.","ให้เหตุผลสนับสนุน","Can the high cost of testing be justified?"],
["inevitable","adj.","หลีกเลี่ยงไม่ได้","Some losses are inevitable during an epidemic."],
["crucial","adj.","สำคัญยิ่ง","Early detection is crucial for control."],
["detrimental","adj.","เป็นผลเสีย","Overcrowding is detrimental to animal welfare."],
["beneficial","adj.","เป็นประโยชน์","Clean water is beneficial for both animals and people."]]},
{theme:"สาธารณสุขและโรคติดต่อจากสัตว์", words:[
["spillover","n.","การข้ามจากสัตว์สู่คน (ของเชื้อโรค)","Bats are linked to the spillover of several viruses."],
["reservoir","n.","แหล่งรังโรค","Wild birds are a reservoir of avian influenza."],
["host","n.","โฮสต์, สิ่งมีชีวิตที่เชื้ออาศัยอยู่","The parasite needs a snail as an intermediate host."],
["immunity","n.","ภูมิคุ้มกัน","Maternal immunity protects young piglets."],
["incubation period","n.","ระยะฟักตัว","The incubation period of rabies can be several months."],
["susceptible","adj.","ไวต่อการติดเชื้อ","Young animals are more susceptible to infection."],
["pandemic","n.","การระบาดใหญ่ทั่วโลก","COVID-19 was a global pandemic."],
["endemic","adj.","เป็นโรคประจำถิ่น","FMD is endemic in parts of Southeast Asia."],
["epidemic","n.","การระบาดอย่างกว้างขวาง","The epidemic spread to four provinces."],
["notifiable","adj.","ต้องแจ้ง (ต่อทางการ)","Avian influenza is a notifiable disease."]]},
{theme:"วัคซีน", words:[
["vaccinate","v.","ฉีดวัคซีน","All dogs should be vaccinated against rabies."],
["booster","n.","การฉีดกระตุ้น","A booster is given four weeks after the first dose."],
["coverage","n.","ความครอบคลุม","Vaccination coverage must reach 80% to stop spread."],
["cold chain","n.","ระบบลูกโซ่ความเย็น","Vaccines lose potency if the cold chain breaks."],
["antibody","n.","แอนติบอดี, สารภูมิต้านทาน","Blood tests showed high antibody levels."],
["antigen","n.","แอนติเจน","The vaccine contains inactivated antigen."],
["herd immunity","n.","ภูมิคุ้มกันหมู่","Herd immunity protects animals that cannot be vaccinated."],
["attenuated","adj.","ที่ทำให้เชื้ออ่อนฤทธิ์","This is a live attenuated vaccine."],
["potency","n.","ความแรง (ของวัคซีนหรือยา)","Heat reduces vaccine potency."],
["campaign","n.","แคมเปญ, การรณรงค์","The government launched a vaccination campaign."]]},
{theme:"ห้องปฏิบัติการ", words:[
["specimen","n.","สิ่งส่งตรวจ","Label every specimen with the date and farm name."],
["culture","n.","การเพาะเชื้อ","A bacterial culture confirmed Salmonella."],
["stain","n.","สีย้อม","Gram stain helps identify bacteria."],
["centrifuge","n.","เครื่องปั่นเหวี่ยง","Spin the blood in a centrifuge to separate serum."],
["assay","n.","การทดสอบ (ทางห้องปฏิบัติการ)","An ELISA assay was used to detect antibodies."],
["sterile","adj.","ปลอดเชื้อ","Use sterile tubes for sample collection."],
["reagent","n.","สารเคมีที่ใช้ทดสอบ","Store the reagents in the refrigerator."],
["false positive","n.","ผลบวกลวง","A false positive result can lead to unnecessary culling."],
["sensitivity","n.","ความไว (ของการทดสอบ)","A test with high sensitivity misses few cases."],
["confirm","v.","ยืนยัน","PCR was used to confirm the diagnosis."]]},
{theme:"ศัลยกรรมและยาสลบ", words:[
["anaesthesia","n.","การระงับความรู้สึก, ยาสลบ","The dog was placed under general anaesthesia."],
["incision","n.","แผลผ่าตัด, การกรีด","Make a small incision along the midline."],
["suture","n.","ไหมเย็บแผล, การเย็บ","The sutures can be removed after ten days."],
["aseptic","adj.","ปราศจากเชื้อ","Aseptic technique prevents surgical infections."],
["haemorrhage","n.","การตกเลือด","The surgeon controlled the haemorrhage quickly."],
["sedation","n.","การทำให้สงบ","Mild sedation made the examination easier."],
["postoperative","adj.","หลังผ่าตัด","Postoperative pain should be managed carefully."],
["wound","n.","บาดแผล","Clean the wound with saline."],
["castration","n.","การตอน","Castration of piglets should be done with pain relief."],
["recovery","n.","การฟื้นตัว","Recovery from anaesthesia took about an hour."]]},
{theme:"ระบบสืบพันธุ์", words:[
["oestrus","n.","การเป็นสัด","Signs of oestrus include mounting and restlessness."],
["gestation","n.","การตั้งท้อง, ระยะอุ้มท้อง","Gestation in sows lasts about 114 days."],
["artificial insemination","n.","การผสมเทียม","Artificial insemination allows the use of better bulls."],
["fertility","n.","ความสมบูรณ์พันธุ์","Poor nutrition reduces fertility."],
["dystocia","n.","การคลอดยาก","Dystocia is more common in first-calf heifers."],
["placenta","n.","รก","A retained placenta can cause infection."],
["lactation","n.","การให้นม","Energy needs are highest in early lactation."],
["abortion","n.","การแท้ง","Brucellosis can cause abortion in cattle."],
["heifer","n.","โคสาว (ยังไม่เคยคลอด)","The heifer was bred at 15 months of age."],
["offspring","n.","ลูกหลาน","Healthy parents produce healthy offspring."]]},
{theme:"โภชนาการสัตว์", words:[
["nutrient","n.","สารอาหาร","Grass is low in some important nutrients."],
["deficiency","n.","การขาด (สารอาหาร)","Iron deficiency causes anaemia in piglets."],
["supplement","n.","อาหารเสริม","Mineral supplements were given during the dry season."],
["ration","n.","สูตรอาหาร (ต่อวัน)","The ration was balanced for protein and energy."],
["digestible","adj.","ย่อยได้","Young grass is more digestible than old straw."],
["forage","n.","พืชอาหารสัตว์","Good forage reduces the need for concentrates."],
["mineral","n.","แร่ธาตุ","Cattle need minerals such as calcium and phosphorus."],
["malnutrition","n.","ภาวะทุพโภชนาการ","Malnutrition weakens the immune system."],
["concentrate","n.","อาหารข้น","Dairy cows receive concentrate after milking."],
["appetite","n.","ความอยากอาหาร","Loss of appetite is often the first sign of illness."]]},
{theme:"เศรษฐกิจและการพัฒนา", words:[
["smallholder","n.","เกษตรกรรายย่อย","Most pigs in Laos are raised by smallholders."],
["subsidy","n.","เงินอุดหนุน","The government offers a subsidy for vaccines."],
["market access","n.","การเข้าถึงตลาด","Disease-free status improves market access."],
["profitable","adj.","มีกำไร","Fish farming can be profitable with good management."],
["investment","n.","การลงทุน","Better housing is a good long-term investment."],
["poverty","n.","ความยากจน","Livestock can help families escape poverty."],
["sustainable","adj.","ยั่งยืน","We need sustainable ways to produce more food."],
["value chain","n.","ห่วงโซ่คุณค่า","The study mapped the pork value chain from farm to market."],
["revenue","n.","รายได้","Egg sales are the main source of revenue."],
["cost-effective","adj.","คุ้มค่าเมื่อเทียบกับต้นทุน","Vaccination is the most cost-effective control measure."]]},
{theme:"นโยบายและองค์กรระหว่างประเทศ", words:[
["policy","n.","นโยบาย","A national rabies policy was approved last year."],
["regulation","n.","กฎระเบียบ","New regulations control the sale of antibiotics."],
["guideline","n.","แนวทางปฏิบัติ","Follow the WOAH guidelines for sample shipment."],
["implement","v.","นำไปปฏิบัติ","The plan will be implemented in ten districts."],
["capacity building","n.","การเสริมสร้างขีดความสามารถ","The project focuses on capacity building for local vets."],
["collaboration","n.","ความร่วมมือ","Collaboration between ministries is essential."],
["partnership","n.","หุ้นส่วน, ความเป็นพันธมิตร","FAO works in partnership with national governments."],
["funding","n.","เงินทุน","The programme depends on international funding."],
["mandate","n.","อาณัติ, ภารกิจที่ได้รับมอบหมาย","The organisation has a mandate to improve animal health."],
["evaluate","v.","ประเมินผล","We evaluated the project after two years."]]},
{theme:"สื่อสารกับเกษตรกร", words:[
["advise","v.","แนะนำ","I advised the farmer to separate the sick pigs."],
["reassure","v.","ทำให้สบายใจ","The vet reassured the owner that the cow would recover."],
["concern","n.","ความกังวล","Farmers raised concerns about the cost of feed."],
["persuade","v.","โน้มน้าว","It took time to persuade villagers to vaccinate."],
["awareness","n.","การรับรู้, ความตระหนัก","The campaign raised awareness of rabies."],
["misconception","n.","ความเข้าใจผิด","A common misconception is that sick meat is safe if cooked."],
["practical","adj.","ใช้ได้จริง","Give simple, practical advice."],
["feedback","n.","ความคิดเห็นตอบกลับ","We asked farmers for feedback on the training."],
["trust","n.","ความไว้วางใจ","Building trust with farmers takes time."],
["convey","v.","สื่อสาร, ถ่ายทอด","Use pictures to convey key messages."]]},
{theme:"สิ่งแวดล้อมและสภาพอากาศ", words:[
["climate change","n.","การเปลี่ยนแปลงสภาพภูมิอากาศ","Climate change may increase vector-borne diseases."],
["drought","n.","ภัยแล้ง","The drought caused a shortage of fodder."],
["flooding","n.","น้ำท่วม","Flooding spread leptospirosis in the village."],
["emission","n.","การปล่อย (ก๊าซ)","Cattle produce methane emissions."],
["heat stress","n.","ภาวะเครียดจากความร้อน","Heat stress reduces milk production."],
["resilience","n.","ความสามารถในการฟื้นตัว, ความยืดหยุ่น","Diverse farms show greater resilience to shocks."],
["adapt","v.","ปรับตัว","Local breeds adapt well to hot weather."],
["degradation","n.","ความเสื่อมโทรม","Overgrazing leads to land degradation."],
["seasonal","adj.","ตามฤดูกาล","Some diseases show a seasonal pattern."],
["pollution","n.","มลพิษ","Farm waste can cause water pollution."]]},
{theme:"ข้อมูลและสถิติ", words:[
["average","n.","ค่าเฉลี่ย","The average herd size was 12 cattle."],
["median","n.","ค่ามัธยฐาน","The median age of the dogs was three years."],
["percentage","n.","ร้อยละ","A high percentage of samples were positive."],
["estimate","v.","ประมาณการ","We estimated the cost of the outbreak."],
["trend","n.","แนวโน้ม","There is an upward trend in poultry production."],
["survey","n.","การสำรวจ","The survey covered 300 households."],
["analyse","v.","วิเคราะห์","Data were analysed using R software."],
["interpret","v.","ตีความ","Results should be interpreted with caution."],
["outlier","n.","ค่าผิดปกติ (ที่ต่างจากกลุ่มมาก)","One farm was an outlier with very high mortality."],
["confidence interval","n.","ช่วงความเชื่อมั่น","The prevalence was 15% (95% confidence interval 10–20%)."]]},
{theme:"อีเมลและการประชุม", words:[
["agenda","n.","วาระการประชุม","The first item on the agenda is the budget."],
["deadline","n.","กำหนดส่ง","The deadline for the report is Friday."],
["follow up","phr. v.","ติดตามผล","I will follow up with the district office tomorrow."],
["attach","v.","แนบ (ไฟล์)","Please find the report attached."],
["clarify","v.","ชี้แจง, ทำให้ชัดเจน","Could you clarify the sampling method?"],
["postpone","v.","เลื่อนออกไป","The meeting was postponed until next week."],
["minutes","n.","บันทึกการประชุม","She took the minutes of the meeting."],
["propose","v.","เสนอ","I propose that we visit the farms in March."],
["available","adj.","ว่าง, พร้อม","Are you available for a call on Monday?"],
["regarding","prep.","เกี่ยวกับ","I am writing regarding the training workshop."]]},
{theme:"ความปลอดภัยอาหาร", words:[
["food safety","n.","ความปลอดภัยของอาหาร","Vets protect food safety from farm to table."],
["residue","n.","สารตกค้าง","Antibiotic residues were found in the meat."],
["slaughterhouse","n.","โรงฆ่าสัตว์","Every animal is inspected at the slaughterhouse."],
["inspection","n.","การตรวจ","Meat inspection detects diseased carcasses."],
["hygiene","n.","สุขอนามัย","Good hygiene prevents food poisoning."],
["spoilage","n.","การเน่าเสีย","Refrigeration slows spoilage."],
["traceability","n.","การตรวจสอบย้อนกลับ","Ear tags improve traceability of cattle."],
["shelf life","n.","อายุการเก็บรักษา","Vacuum packing extends the shelf life of meat."],
["foodborne","adj.","ที่เกิดจากอาหาร","Salmonella is a common foodborne pathogen."],
["contamination","n.","การปนเปื้อน","Cross-contamination can occur on cutting boards."]]},
{theme:"กายวิภาคพื้นฐาน", words:[
["abdomen","n.","ช่องท้อง","The abdomen was swollen and painful."],
["thorax","n.","ช่องอก","X-rays of the thorax showed pneumonia."],
["rumen","n.","กระเพาะรูเมน","The rumen contains millions of microbes."],
["liver","n.","ตับ","Liver flukes damage the liver of cattle."],
["kidney","n.","ไต","The kidneys filter waste from the blood."],
["spleen","n.","ม้าม","An enlarged spleen is a sign of ASF."],
["lymph node","n.","ต่อมน้ำเหลือง","Swollen lymph nodes suggest infection."],
["trachea","n.","หลอดลม","The tube was placed in the trachea."],
["intestine","n.","ลำไส้","Worms were found in the small intestine."],
["udder","n.","เต้านม (ของสัตว์)","Mastitis makes the udder hot and hard."]]},
{theme:"กริยาบรรยายโรค", words:[
["spread","v.","แพร่กระจาย","The disease spread rapidly through the village."],
["affect","v.","ส่งผลกระทบ, ทำให้ป่วย","The virus affects pigs of all ages."],
["prevent","v.","ป้องกัน","Clean water helps prevent diarrhoea."],
["detect","v.","ตรวจพบ","The test can detect the virus within hours."],
["eradicate","v.","กำจัดให้หมดสิ้น","Rinderpest was eradicated in 2011."],
["emerge","v.","อุบัติขึ้น, เกิดขึ้นใหม่","New diseases often emerge at the human–animal interface."],
["persist","v.","คงอยู่","The virus can persist in frozen meat."],
["trigger","v.","กระตุ้นให้เกิด","Stress can trigger disease in carrier animals."],
["worsen","v.","แย่ลง","The cough worsened over three days."],
["recover","v.","ฟื้นตัว, หายป่วย","Most animals recover within a week."]]},
{theme:"คุณลักษณะส่วนตัว (สัมภาษณ์งานและ CV)", words:[
["reliable","adj.","เชื่อถือได้","My supervisor describes me as reliable and hard-working."],
["adaptable","adj.","ปรับตัวได้ดี","Field work requires staff who are adaptable."],
["motivated","adj.","มีแรงจูงใจ, กระตือรือร้น","I am highly motivated to work in animal health."],
["proactive","adj.","ทำงานเชิงรุก, คิดล่วงหน้า","She took a proactive approach to disease reporting."],
["collaborative","adj.","ทำงานร่วมกับผู้อื่นได้ดี","The project needs a collaborative team player."],
["meticulous","adj.","พิถีพิถัน, ละเอียดรอบคอบ","Lab work requires meticulous record keeping."],
["committed","adj.","ทุ่มเท, มุ่งมั่น","I am committed to improving rural livelihoods."],
["empathetic","adj.","เข้าใจความรู้สึกผู้อื่น","An empathetic vet listens carefully to farmers."],
["organised","adj.","มีระบบ, เป็นระเบียบ","Being organised helps me meet deadlines."],
["initiative","n.","ความคิดริเริ่ม","He showed initiative by starting a training group."]]},
{theme:"สังคมและการพัฒนา (Speaking Part 3)", words:[
["urbanisation","n.","การขยายตัวของเมือง","Urbanisation increases the demand for meat."],
["rural","adj.","ชนบท","Many rural families depend on livestock."],
["population growth","n.","การเพิ่มของประชากร","Population growth puts pressure on food supplies."],
["consumption","n.","การบริโภค","Pork consumption has doubled in ten years."],
["globalisation","n.","โลกาภิวัตน์","Globalisation makes it easier for diseases to travel."],
["infrastructure","n.","โครงสร้างพื้นฐาน","Poor road infrastructure delays vaccine delivery."],
["affordable","adj.","ราคาที่จ่ายได้","Vaccines must be affordable for smallholders."],
["access","n.","การเข้าถึง","Remote villages have little access to vets."],
["migration","n.","การย้ายถิ่น","Young people's migration to cities leaves fewer farm workers."],
["demand","n.","ความต้องการ (ของตลาด)","Demand for fish is rising across Asia."]]},
{theme:"คำนามวิชาการ (Academic Word List)", words:[
["approach","n.","แนวทาง, วิธีการ","We need an integrated approach to disease control."],
["evidence","n.","หลักฐาน","There is strong evidence that the vaccine works."],
["factor","n.","ปัจจัย","Several factors contributed to the outbreak."],
["framework","n.","กรอบ (แนวคิด)","The study used a One Health framework."],
["impact","n.","ผลกระทบ","ASF had a huge impact on pig farmers."],
["issue","n.","ประเด็น, ปัญหา","Antimicrobial resistance is a global issue."],
["method","n.","วิธีการ","This method is quick and cheap."],
["principle","n.","หลักการ","The basic principles of biosecurity are simple."],
["role","n.","บทบาท","Village vets play a key role in surveillance."],
["strategy","n.","กลยุทธ์","The national strategy aims to eliminate rabies by 2030."]]}
];
